spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2487302491m
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
server:
  port: 8125
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.service.entity
  configuration:
    map-underscore-to-camel-case: true
